In [60]:
import pandas as pd 
import numpy as np

In [61]:
horas_cif = pd.read_excel('..\data\hora2023.XLS')

In [62]:
horas_cif

,Fecha,00,01,02,03,04,05,06,07,08,...,15,16,17,18,19,20,21,22,23,Totales
0,2023-01-01 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,9.0,7.0,9.0,17.0,5.0,1.0,49.0
1,2023-01-02 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,4.0,7.0,3.0,2.0,8.0,9.0,9.0,5.0,0.0,101.0
2,2023-01-03 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,4.0,5.0,10.0,8.0,4.0,9.0,18.0,6.0,0.0,113.0
3,2023-01-04 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,6.0,4.0,8.0,9.0,6.0,10.0,11.0,5.0,0.0,125.0
4,2023-01-05 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,...,6.0,3.0,10.0,16.0,5.0,17.0,19.0,3.0,2.0,138.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2023-06-28 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,12.0,14.0,15.0,13.0,8.0,6.0,16.0,7.0,0.0,149.0
179,2023-06-29 00:00:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,7.0,11.0,7.0,18.0,9.0,6.0,8.0,5.0,0.0,127.0
180,2023-06-30 00:00:00,9,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,6.0,9.0,18.0,18.0,14.0,14.0,17.0,9.0,1.0,161.0
181,Totales,173,57.0,19.0,0.0,0.0,6.0,0.0,0.0,645.0,...,1199.0,1352.0,2012.0,2087.0,2035.0,2432.0,2352.0,1551.0,490.0,24268.0
182,Fecha Impresi√≥n: 09/07/2023 19:46:29,Hoja 1 de 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
horas_cif.drop(columns=['00','01','02','03','04','05','06','07'], inplace=True)

In [64]:
horas_cif.drop([181,182], inplace=True)

In [65]:
horas_cif['Fecha'] = pd.to_datetime(horas_cif['Fecha'])

In [66]:
# df = horas_cif.copy().set_index('Fecha', inplace=True)

In [67]:
# df.resample('D').sum()

In [69]:
df_por_dias = horas_cif.groupby(horas_cif['Fecha'].dt.weekday).sum()

C:\Users\nicol\AppData\Local\Temp\ipykernel_17856\4272512788.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_por_dias = horas_cif.groupby(horas_cif['Fecha'].dt.weekday).sum()

In [70]:
df_por_dias

,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,Totales
Fecha,,,,,,,,,,,,,,,,,
0,115.0,166.0,165.0,201.0,258.0,310.0,208.0,190.0,242.0,302.0,272.0,287.0,325.0,230.0,147.0,13.0,3432.0
1,108.0,165.0,163.0,214.0,275.0,269.0,236.0,209.0,220.0,280.0,273.0,301.0,309.0,299.0,192.0,15.0,3528.0
2,130.0,183.0,183.0,217.0,242.0,316.0,266.0,213.0,205.0,314.0,296.0,244.0,353.0,304.0,170.0,9.0,3645.0
3,142.0,173.0,184.0,225.0,269.0,280.0,208.0,212.0,218.0,295.0,362.0,293.0,370.0,317.0,212.0,24.0,3784.0
4,116.0,159.0,173.0,202.0,261.0,333.0,241.0,201.0,247.0,359.0,408.0,329.0,403.0,476.0,298.0,204.0,4571.0
5,34.0,138.0,147.0,200.0,211.0,230.0,186.0,174.0,218.0,244.0,251.0,286.0,360.0,362.0,318.0,204.0,3655.0
6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,218.0,225.0,295.0,312.0,364.0,214.0,21.0,1653.0

In [73]:
enero = horas_cif.iloc[0:31]

In [74]:
enero.groupby(enero['Fecha'].dt.weekday).sum()

C:\Users\nicol\AppData\Local\Temp\ipykernel_17856\266207045.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  enero.groupby(enero['Fecha'].dt.weekday).sum()

,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,Totales
Fecha,,,,,,,,,,,,,,,,,
0,28.0,32.0,28.0,47.0,41.0,45.0,41.0,33.0,45.0,47.0,33.0,45.0,58.0,48.0,27.0,6.0,604.0
1,25.0,20.0,37.0,42.0,46.0,50.0,34.0,46.0,41.0,50.0,40.0,35.0,49.0,61.0,56.0,3.0,635.0
2,11.0,27.0,30.0,25.0,39.0,48.0,33.0,27.0,19.0,38.0,39.0,27.0,44.0,54.0,14.0,0.0,475.0
3,22.0,30.0,37.0,28.0,41.0,28.0,24.0,30.0,21.0,30.0,51.0,34.0,51.0,65.0,31.0,4.0,527.0
4,16.0,33.0,32.0,20.0,45.0,43.0,41.0,21.0,21.0,51.0,43.0,43.0,56.0,65.0,37.0,36.0,619.0
5,6.0,17.0,14.0,19.0,20.0,41.0,24.0,25.0,24.0,29.0,31.0,34.0,55.0,74.0,58.0,34.0,505.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,21.0,30.0,47.0,63.0,69.0,47.0,3.0,282.0

In [75]:
meses = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']

In [86]:
months = {'enero': 31, 'febrero':28, 'marzo': 31, 'abril': 30, 'mayo': 31, 'junio':30, 'julio': 31, 'agosto': 31, 'septiembre':30, 'octubre':31, 'noviembre':30, 'diciembre':31}

In [146]:
febrero = horas_cif.iloc[31:59]
marzo = horas_cif.iloc[months[febrero]:56]

TypeError: unhashable type: 'DataFrame'

In [142]:
sd

,Fecha,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,Totales
0,2023-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,9.0,7.0,9.0,17.0,5.0,1.0,49.0
1,2023-01-02,6.0,6.0,5.0,12.0,5.0,11.0,9.0,4.0,7.0,3.0,2.0,8.0,9.0,9.0,5.0,0.0,101.0
2,2023-01-03,6.0,5.0,11.0,7.0,5.0,12.0,3.0,4.0,5.0,10.0,8.0,4.0,9.0,18.0,6.0,0.0,113.0
3,2023-01-04,2.0,7.0,12.0,9.0,12.0,14.0,10.0,6.0,4.0,8.0,9.0,6.0,10.0,11.0,5.0,0.0,125.0
4,2023-01-05,10.0,12.0,6.0,7.0,12.0,6.0,4.0,6.0,3.0,10.0,16.0,5.0,17.0,19.0,3.0,2.0,138.0
5,2023-01-06,4.0,6.0,11.0,8.0,11.0,10.0,15.0,12.0,10.0,16.0,9.0,18.0,17.0,18.0,10.0,8.0,192.0
6,2023-01-07,3.0,10.0,5.0,12.0,6.0,18.0,10.0,5.0,4.0,7.0,12.0,7.0,17.0,21.0,10.0,6.0,153.0
7,2023-01-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0,3.0,12.0,10.0,13.0,12.0,1.0,60.0
8,2023-01-09,11.0,4.0,8.0,10.0,7.0,3.0,6.0,8.0,13.0,6.0,4.0,10.0,11.0,9.0,4.0,2.0,116.0
9,2023-01-10,4.0,2.0,8.0,9.0,18.0,12.0,10.0,8.0,7.0,11.0,8.0,1.0,8.0,17.0,10.0,2.0,135.0
10,2023-01-11,2.0,9.0,4.0,1.0,5.0,4.0,8.0,7.0,8.0,10.0,13.0,7.0,13.0,12.0,3.0,0.0,106.0
11,2023-01-12,6.0,3.0,10.0,8.0,9.0,6.0,8.0,8.0,8.0,14.0,11.0,10.0,14.0,13.0,8.0,0.0,136.0
12,2023-01-13,9.0,13.0,12.0,3.0,18.0,15.0,15.0,3.0,6.0,16.0,20.0,7.0,10.0,28.0,10.0,10.0,198.0
13,2023-01-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,3.0,7.0,13.0,14.0,20.0,14.0,83.0
14,2023-01-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,10.0,9.0,18.0,12.0,8.0,0.0,61.0
15,2023-01-16,5.0,10.0,3.0,11.0,7.0,7.0,12.0,6.0,11.0,10.0,8.0,11.0,16.0,13.0,8.0,0.0,138.0
16,2023-01-17,7.0,5.0,7.0,8.0,10.0,8.0,9.0,14.0,9.0,7.0,8.0,11.0,11.0,7.0,12.0,0.0,133.0
17,2023-01-18,4.0,8.0,9.0,9.0,15.0,11.0,9.0,8.0,3.0,11.0,12.0,11.0,8.0,15.0,3.0,0.0,136.0
18,2023-01-19,2.0,7.0,10.0,7.0,10.0,3.0,2.0,9.0,2.0,3.0,10.0,9.0,5.0,15.0,9.0,2.0,105.0
19,2023-01-20,0.0,4.0,7.0,5.0,14.0,12.0,5.0,5.0,1.0,2.0,7.0,10.0,12.0,10.0,4.0,6.0,105.0
20,2023-01-21,1.0,2.0,3.0,4.0,4.0,11.0,6.0,9.0,10.0,10.0,8.0,6.0,9.0,18.0,17.0,6.0,124.0
21,2023-01-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,8.0,16.0,11.0,12.0,0.0,52.0
22,2023-01-23,1.0,6.0,7.0,6.0,11.0,10.0,4.0,9.0,4.0,9.0,9.0,3.0,8.0,9.0,4.0,4.0,104.0
23,2023-01-24,4.0,1.0,6.0,9.0,8.0,9.0,2.0,8.0,9.0,9.0,5.0,11.0,10.0,10.0,9.0,0.0,110.0
24,2023-01-25,3.0,3.0,5.0,6.0,7.0,19.0,6.0,6.0,4.0,9.0,5.0,3.0,13.0,16.0,3.0,0.0,108.0
25,2023-01-26,4.0,8.0,11.0,6.0,10.0,13.0,10.0,7.0,8.0,3.0,14.0,10.0,15.0,18.0,11.0,0.0,148.0
26,2023-01-27,3.0,10.0,2.0,4.0,2.0,6.0,6.0,1.0,4.0,17.0,7.0,8.0,17.0,9.0,13.0,12.0,124.0
27,2023-01-28,2.0,5.0,6.0,3.0,10.0,12.0,8.0,11.0,4.0,6.0,8.0,14.0,16.0,21.0,11.0,8.0,145.0
28,2023-01-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,5.0,11.0,10.0,16.0,10.0,1.0,60.0
29,2023-01-30,5.0,6.0,5.0,8.0,11.0,14.0,10.0,6.0,10.0,19.0,10.0,13.0,14.0,8.0,6.0,0.0,145.0
30,2023-01-31,4.0,7.0,5.0,9.0,5.0,9.0,10.0,12.0,11.0,13.0,11.0,8.0,11.0,9.0,19.0,1.0,144.0